name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: exclusive_arc
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        ruby:
          - 3.2
          - 2.7
        rails: 
          - 6.1
          - 7.0
        database_adapter:
          - sqlite3
          - postgresql

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env: 
          RAILS_VERSION: ${{ matrix.rails }}
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        env:
          RAILS_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          RAILS_VERSION: ${{ matrix.rails }}
          DATABASE_ADAPTER: ${{ matrix.database_adapter }}
        run: |
          bundle exec rake
