name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }} / Adapter ${{ matrix.database_adapter }}

    strategy:
      matrix:
        ruby:
          - "3.3"
        rails: 
          - "6.1"
          - "7.0.8.4"
          - "7.1.4"
          - "7.2.1"
        include:
          - rails: "6.1"
            ruby: "2.7"
          - rails: "8.0.0.beta1"
            ruby: "3.3"
        database_adapter:
          - sqlite3
          - postgresql
          - mysql2

    steps:
      - uses: actions/checkout@v4
      
      - name: "setup mysql"
        if: ${{ matrix.database_adapter == 'mysql2' }}
        run: |
          sudo systemctl start mysql.service
          sudo mysql -u root --password=root -e "CREATE DATABASE exclusive_arc"
          sudo mysql -u root --password=root -e "CREATE USER 'runner'@'localhost' IDENTIFIED BY 'runner'"
          sudo mysql -u root --password=root -e "GRANT ALL ON exclusive_arc.* TO 'runner'@'localhost';"

      - name: "setup postgres"
        if: ${{ matrix.database_adapter == 'postgresql' }}
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres psql -c "CREATE USER runner WITH SUPERUSER PASSWORD 'runner'"
          sudo -u postgres createdb exclusive_arc

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env: 
          RAILS_VERSION: ${{ matrix.rails }}
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          
      - name: Run the default task
        env:
          RAILS_ENV: test
          RAILS_VERSION: ${{ matrix.rails }}
          DATABASE_USER: runner
          DATABASE_PASSWORD: runner
          DATABASE_ADAPTER: ${{ matrix.database_adapter }}
          
        run: |
          bundle exec rake
