name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: exclusive_arc
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 3306:3306
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: exclusive_arc
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        ruby:
          - "3.3"
          - "2.7"
        rails: 
          - "6.1"
          - "7.0"
          - "7.1"
        database_adapter:
          - sqlite3
          - postgresql
          - trilogy

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env: 
          RAILS_VERSION: ${{ matrix.rails }}
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        env:
          RAILS_ENV: test
          RAILS_VERSION: ${{ matrix.rails }}
          DATABASE_USER: user
          DATABASE_PASSWORD: password
          DATABASE_ADAPTER: ${{ matrix.database_adapter }}
        run: |
          bundle exec rake
