name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }} / Adapter ${{ matrix.database_adapter }}

    strategy:
      matrix:
        ruby:
          - "3.3"
          - "2.7"
        rails: 
          - "6.1"
          - "7.0"
          - "7.1"
        database_adapter:
          - sqlite3
          - postgresql
          - trilogy

    steps:
      - uses: actions/checkout@v4
      
      - name: "setup mysql"
        if: ${{ matrix.database_adapter == 'trilogy' }}
        run: |
          sudo systemctl start mysql.service
          sudo mysql -u root --password=root -e 'create database exclusive_arc'

      - name: "setup postgres"
        if: ${{ matrix.database_adapter == 'postgresql' }}
        env:
          DATABASE_USER: postgres
        run: |
          sudo systemctl start postgresql.service
          sudo -u postgres createdb exclusive_arc
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env: 
          RAILS_VERSION: ${{ matrix.rails }}
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          
      - name: Run the default task
        env:
          RAILS_ENV: test
          RAILS_VERSION: ${{ matrix.rails }}
          DATABASE_ADAPTER: ${{ matrix.database_adapter }}
          
        run: |
          bundle exec rake
